### ISSUE TITLE
Don't export some mixins

### ISSUE THREAD

**Issue by pixel2** [less/less.ruby#37]
Love the syntax and ease of use with Less, but i have a small feature request. Some mixins are only used as just mixins for other classes and there is no need for this class being present in the outputted css-file. It would be nice to have the option to specify that a mixin shouldn't be outputted to the final css but just included in other classes. Maybe by using the variable syntax:

<pre>@mixin {
  background-color: red;
  
  :hover {
    text-decoration; underline;
  }
}</pre>

**Comment by cloudhead** [comment]
A couple people asked about this, I'm looking into the best way to do this, syntax wise.

**Comment by xdissent** [comment]
Since the scope of a mixin is clearly defined, perhaps a mechanism for defining metadata on a per scope basis would be beneficial. No other use cases come to mind, but an "export" property could be just a bit of metadata on a mixin, right?

**Comment by cloudhead** [comment]
I'm liking the @mixin { ... } syntax though, it's pretty clear, and uses similar syntax to variables.

**Comment by jeremyh** [comment]
A colon would make it consistent with variables:

```
@nice-blue: #5B83AD;
@bordered: {
    border: 1px solid black;
}
```

**Comment by jeremyh** [comment]
A mixin with arguments couldn't be exported by Less. Well, it _could_ if there are defaults specified for the arguments, but otherwise it is incomplete by itself.

So, for consistency we could either
1. Only allow mixins with arguments to be specified as non-exported mixins (with an @symbol, as discussed in this thread). Like this:
   
   ```
   @bordered(@size): {
       border: @size solid black;
   }
   ```
2. Or we treat any mixin with parenthesis/arguments as a non-exported mixin. So this would be the syntax for stopping a normal mixin from being exported:
   
   ```
   .bordered() {
   }
   ```

**Comment by xdissent** [comment]
I just started trying to visualize how I'd refactor a project I'm working on when these features become available. I found the need for manually silencing a mixin was reduced to zero if mixins can take arguments. So my vote goes for the second method since in my opinion, the use of the @ symbol seems to be catering to a fairly distant edge case.

**Comment by cloudhead** [comment]
I really like jeremy's 2nd idea, it's not very pretty, but it doesn't add new syntax either (as far as mixins with arguments go). My only objection is that if a mixin doesn't export, then it's irrelevant whether it's a class or an id, and it's more comparable to a variable, and therefore shouldn't need `.#` at all. If you remove it though, it looks like a tag.

Anyone else want to chime in?

**Comment by xdissent** [comment]
The ambiguity of syntax for mixins bothers me _less_ than adding a colon and declaring them like variables since the difference between variables and mixins is pretty distinct. Also, it would be nice to have the ability to switch between silenced and normal mixins without having to change how they're actually called in classes that use them. With the first method, that would require replacing at least 2 characters in every call, rather than simply adding parenthesis to the mixin definition.

**Comment by liusong1111** [comment]
how to expand css3 expression 

```
 box-shadow:  9px 9px 10px red;
```

to 

```
-moz-box-shadow:9px 9px 10px red;

-webkit-box-shadow:9px 9px 10px red;
```

use mixins discussed above? or introduce more meta-programming syntax?

**Comment by liusong1111** [comment]
Acctually, I want use mixins like a custom css attribute:

```
 @border-shadow: 9px 9px 10px red;
```

Mixins runs as a function(yield real css), written as a declaration(call like a custom css attribute).

The only question is: how many functionality should be introduced from programming language(ruby,etc) into less?

**Comment by cloudhead** [comment]
Yea you would use mixins for that, but it would be most useful if you could pass the values as arguments, which you can't _yet_.

The syntax would look like this:

```
.box-shadow(9px, 9px, 10px, red);
```

**Comment by liusong1111** [comment]
note: @font-face usage

**Comment by liusong1111** [comment]
I prefer:
     @box-shadow: 9px 9px 10px red;
rather than:
    .box-shadow(9px, 9px, 10px, red);
because the first indicates a function call,while the second in CSS always indicates  class selector(pattern match).

consider the following code:

```
ul.main{
  .head{
    color:red;
  }
  .body(9px, 9px, 10px, red);
}
```

use .class1 to reprensent as class selector, mixin defination and mixin call.
that's too much.
I'd like a more explicit way to define and invoke mixins.

**Comment by liusong1111** [comment]
I realize less' mixin is to simulate OO inheritance, and base class selector(Base Class) could be used too, so .class1 is more straightforward.

I should reconsider and take back what I said.

thank you for your great job, giving me much space for imagination :)

**Comment by liusong1111** [comment]
maybe that?

```
@class1, .class1{
      color: red;
 }
```

**Comment by cloudhead** [comment]
```
@box-shadow: 1px 4px 1 1;
```

doesn't work, because that's the syntax for variables.

Explicit mixins might just use:

```
@class1 {}
```

another possibility is

```
!class1 {}
```

which is nice because it's `.class1` with a little bar : )

**Comment by liusong1111** [comment]
Anyway, we just want an approach to define simple functions, under inheritance rules, using CSS way.

I think another useful infrastructure is: 
expand CSS3 statement to several compliant sentences. 

That will be very useful for those who want to use CSS3 features but don't want touch the vary -moz-xx, -webkit-xxx.

If lesscss provides the transform infrastructure directly, or as a sub-project, it will be much attractive. -- as CSS3 becomes more available and will be the next big thing for CSS.

**Comment by cloudhead** [comment]
Closing, 1.2.\* is out with dynamic mixins.
