### ISSUE TITLE
undefined method `has_terminal?`

### ISSUE THREAD

**Issue by jsmestad** [less/less.ruby#47]
when running rake features, we are running into the following error:

<pre><code>undefined method `has_terminal?' for #<LessParser:0x3888fbc> (NoMethodError)</code></pre>

This is using the latest 1.0.14 version of Less.

Full stack trace:

<pre><code>/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby -I "/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/lib:lib" "/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/cucumber" --format pretty features/manage_invitation.feature
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/command.rb:56: warning: parenthesize argument(s) for future version
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine.rb:18: warning: parenthesize argument(s) for future version
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:497: warning: parenthesize argument(s) for future version
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:592: warning: parenthesize argument(s) for future version
undefined method `has_terminal?' for #<LessParser:0x22e41ac> (NoMethodError)
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:4041:in `_nt_ws'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:4040:in `loop'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:4040:in `_nt_ws'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:1095:in `_nt_declaration'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:20:in `_nt_primary'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:18:in `loop'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:18:in `_nt_primary'
/Library/Ruby/Gems/1.8/gems/treetop-1.2.6/lib/treetop/runtime/compiled_parser.rb:18:in `send'
/Library/Ruby/Gems/1.8/gems/treetop-1.2.6/lib/treetop/runtime/compiled_parser.rb:18:in `parse'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine.rb:30:in `parse'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine.rb:43:in `to_css'
/Users/justinsmestad/Documents/Factory/audi_tdi_challenge/config/initializers/less_for_rails.rb:14:in `run'
/Users/justinsmestad/Documents/Factory/audi_tdi_challenge/config/initializers/less_for_rails.rb:13:in `each'
/Users/justinsmestad/Documents/Factory/audi_tdi_challenge/config/initializers/less_for_rails.rb:13:in `run'
/Users/justinsmestad/Documents/Factory/audi_tdi_challenge/config/initializers/less_for_rails.rb:34
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:147:in `load_without_new_constant_marking'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:147:in `load'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:622:in `load_application_initializers'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:621:in `each'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:621:in `load_application_initializers'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:176:in `process'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:113:in `send'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:113:in `run'
/Users/justinsmestad/Documents/Factory/audi_tdi_challenge/config/environment.rb:27
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
/Library/Ruby/Gems/1.8/gems/polyglot-0.2.6/lib/polyglot.rb:55:in `require'
./features/support/env.rb:2
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
/Library/Ruby/Gems/1.8/gems/polyglot-0.2.6/lib/polyglot.rb:55:in `require'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:95:in `require_files'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:104:in `each_lib'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:102:in `each'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:102:in `each_lib'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:95:in `require_files'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:47:in `execute!'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:25:in `execute'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/cucumber:9
</code></pre>

**Comment by cloudhead** [comment]
Problem seems to be that, for a reason which isn't apparent, Less is trying to use your Treetop gem, instead of the version included in `lib/vendor/`. Either the LOAD_PATH is changed somewhere, or maybe the treetop gem was pre-loaded before loading Less.

Does your project use treetop? If so, you could try upgrading to the just released 1.3.0, which has the optimizations I included in the local version and therefore might work.

**Comment by jsmestad** [comment]
I updated to treetop 1.3.0 and now I get the following error:

<pre><code>undefined method `parent=' for true:TrueClass (NoMethodError)
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/syntax_node.rb:12:in `initialize'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/syntax_node.rb:11:in `each'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/syntax_node.rb:11:in `initialize'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/compiled_parser.rb:79:in `new'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/compiled_parser.rb:79:in `instantiate_node'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:2190:in `_nt_id'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:1893:in `_nt_class_id'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:1887:in `loop'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:1887:in `_nt_class_id'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:1719:in `_nt_element'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:967:in `_nt_selector'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:959:in `loop'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:959:in `_nt_selector'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:848:in `_nt_selectors'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:383:in `_nt_ruleset'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:24:in `_nt_primary'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:18:in `loop'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine/parser.rb:18:in `_nt_primary'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/compiled_parser.rb:18:in `send'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/compiled_parser.rb:18:in `parse'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine.rb:30:in `parse'
/Library/Ruby/Gems/1.8/gems/less-1.0.14/lib/less/engine.rb:43:in `to_css'
/Users/justinsmestad/Documents/Factory/audi_tdi_challenge/config/initializers/less_for_rails.rb:14:in `run'
/Users/justinsmestad/Documents/Factory/audi_tdi_challenge/config/initializers/less_for_rails.rb:13:in `each'
/Users/justinsmestad/Documents/Factory/audi_tdi_challenge/config/initializers/less_for_rails.rb:13:in `run'
/Users/justinsmestad/Documents/Factory/audi_tdi_challenge/config/initializers/less_for_rails.rb:34
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:147:in `load_without_new_constant_marking'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:147:in `load'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:622:in `load_application_initializers'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:621:in `each'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:621:in `load_application_initializers'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:176:in `process'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:113:in `send'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:113:in `run'
/Users/justinsmestad/Documents/Factory/audi_tdi_challenge/config/environment.rb:27
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
/Library/Ruby/Gems/1.8/gems/polyglot-0.2.6/lib/polyglot.rb:55:in `require'
./features/support/env.rb:2
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
/Library/Ruby/Gems/1.8/gems/polyglot-0.2.6/lib/polyglot.rb:55:in `require'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:95:in `require_files'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:104:in `each_lib'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:102:in `each'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:102:in `each_lib'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:95:in `require_files'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:47:in `execute!'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:25:in `execute'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/cucumber:9
rake aborted!
</code></pre>

**Comment by cloudhead** [comment]
Hmm, so does your app use Treetop?

**Comment by cloudhead** [comment]
Ok, the reason it's doing that TrueClass thing is that it uses a pre-compiled grammar. I'm in the process of upgrading the gem to use 1.3.0. In the meantime, you can do a `rake compile` in the gem root, and it'll recompile the grammar with your current version of treetop. I tried it myself, and it works.

**Comment by jayzes** [comment]
Looks like it's still doing the same thing after a rake compile:

<pre>
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby -I "/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/lib:lib" "/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/cucumber" --format pretty features/manage_invitation.feature
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/command.rb:56: warning: parenthesize argument(s) for future version
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine.rb:18: warning: parenthesize argument(s) for future version
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:497: warning: parenthesize argument(s) for future version
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:592: warning: parenthesize argument(s) for future version
undefined method `parent=' for true:TrueClass (NoMethodError)
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/syntax_node.rb:12:in `initialize'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/syntax_node.rb:11:in `each'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/syntax_node.rb:11:in `initialize'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/compiled_parser.rb:79:in `new'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/compiled_parser.rb:79:in `instantiate_node'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:2190:in `_nt_id'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:1893:in `_nt_class_id'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:1887:in `loop'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:1887:in `_nt_class_id'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:1719:in `_nt_element'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:967:in `_nt_selector'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:959:in `loop'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:959:in `_nt_selector'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:848:in `_nt_selectors'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:383:in `_nt_ruleset'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:24:in `_nt_primary'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:18:in `loop'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine/parser.rb:18:in `_nt_primary'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/compiled_parser.rb:18:in `send'
/Library/Ruby/Gems/1.8/gems/treetop-1.3.0/lib/treetop/runtime/compiled_parser.rb:18:in `parse'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine.rb:30:in `parse'
/Users/jayzeschin/Projects/audi_tdi_challenge/vendor/gems/less-1.0.14/lib/less/engine.rb:43:in `to_css'
/Users/jayzeschin/Projects/audi_tdi_challenge/config/initializers/less_for_rails.rb:14:in `run'
/Users/jayzeschin/Projects/audi_tdi_challenge/config/initializers/less_for_rails.rb:13:in `each'
/Users/jayzeschin/Projects/audi_tdi_challenge/config/initializers/less_for_rails.rb:13:in `run'
/Users/jayzeschin/Projects/audi_tdi_challenge/config/initializers/less_for_rails.rb:34
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:147:in `load_without_new_constant_marking'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:147:in `load'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:622:in `load_application_initializers'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:621:in `each'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:621:in `load_application_initializers'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:176:in `process'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:113:in `send'
/Library/Ruby/Gems/1.8/gems/rails-2.3.3/lib/initializer.rb:113:in `run'
/Users/jayzeschin/Projects/audi_tdi_challenge/config/environment.rb:27
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
/Library/Ruby/Gems/1.8/gems/polyglot-0.2.6/lib/polyglot.rb:55:in `require'
./features/support/env.rb:2
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
/Library/Ruby/Gems/1.8/gems/polyglot-0.2.6/lib/polyglot.rb:55:in `require'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:95:in `require_files'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:104:in `each_lib'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:102:in `each'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:102:in `each_lib'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:95:in `require_files'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:47:in `execute!'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/../lib/cucumber/cli/main.rb:25:in `execute'
/Library/Ruby/Gems/1.8/gems/cucumber-0.3.11/bin/cucumber:9
rake aborted!
Command failed with status (1): [/System/Library/Frameworks/Ruby.framework/...]
</pre>

I think the only reason treetop is getting loaded first is because cucumber is using it to parse the feature files.  I vendored less into the app and ran rake compile, then when that didn't work I tried rake compile in the system gem directory, with the same effect.  As a workaround for right now,  I think I'll try running the less executable from the cucumber environment to parse the files to avoid the loading conflict.

**Comment by cloudhead** [comment]
Aha that's right, cucumber uses Treetop : ).  Pushing the new gem right now, tell me if it makes any difference.

**Comment by cloudhead** [comment]
closing this, feel free to reopen it or open a new ticket if you still have the problem.
