### ISSUE TITLE
Error with multiple values comma-separeted

### ISSUE THREAD

**Issue by roncioso** [less/less.ruby#63]
When setting a property with multiple values comma-separated, less returns an error.
In my case this was caused by text-shadow: 
    .class { 
        text-shadow: -1px -1px 1px red, 5px 5px 5px yellow;
    }

**Comment by macavon** [comment]
As far as I can see, the only properties that allow comma-separated lists in CSS 2.1 are font-family, which is treated as a special case in entity.tt, cursor and voice-family, but there are quite a few other cases in CSS 3, including text-shadow and any background property where there are multiple backgrounds. I also noticed that CSS transitions use this idiom a lot. There are probably more, but with CSS3 being split over all those different documents it's a bit hard to find them all in a hurry.

It would seem easiest to follow the grammar in the CSS spec and allow commas within values anywhere, even though this would let through some invalid CSS. Otherwise, someone would have to track down all the cases in all the CSS 3 documents and the Webkit and Mozilla extensions where commas are actually used.

**Comment by cloudhead** [comment]
yep, font-family works, but everything else doesn't. I'm working on a patch to fix this.

**Comment by roncioso** [comment]
In css3 there are many multivalue properties. Another problem there's with @font-face and local() value for src

**Comment by cloudhead** [comment]
should be fixed on 1.2.1 (github only for now) - if anyone wants to test it, be my guest.
